cc_binary(
    name = "render_object.so",
    srcs = ["render_object.cc"],
    linkshared = 1,
    deps = [
        "//cpp/lib:camera",
        "//cpp/lib:common",
        "//cpp/lib:egl_rendering",
    ],
)
