package(default_visibility = ["//:__subpackages__"])

proto_library(
    name = "dataset_proto",
    srcs = ["dataset.proto"],
)

cc_proto_library(
    name = "dataset_cc_proto",
    deps = [":dataset_proto"],
)
